### ISSUE TITLE
Combine socketplane/libovsdb and ebay/libovsdb

### ISSUE THREAD

**Issue by dave-tucker** [eBay/libovsdb#36]
# Background

:wave: I'm one of the original authors of `libovsdb` and the only active maintainer left of `socketplane/libovsdb`.

I note in your README that your motivation for forking the repository was as follows:
```
This fork has been created to encourage changes and patches to ensure this version of the library works with go-ovn.
```
This sounds like a practical difference, not a philosophical one. You had changes to make, there hadn't been any activity on the upstream repository for a while, and you had a job to do.

# Motivation 

Thanks to `libovsdb`s usage in `go-ovn`, and for my involvement with `ovn-kubernetes` I've been able to find time to work on `libovsdb` again.

Aside from the changes I made in `socketplane/libovsdb` I've contributed #35, and I have plans with @amorenoz to get #31 merged soon so we can generate code for clients. Once we've tested this with `go-ovn`, I'd like to help pull together a `v1.0` release. After which, I have a `Server` implementation that I'm planning to contribute in the coming months which can be used to try out various data storage formats, or for testing the client.

I can't maintain `socketplane/libvosdb` on my own and it's unclear how this fork is being managed.
The `MAINTAINERS` file still has my name in it :wink: 

# Proposal 

I would like to propose that we work together and merge these two repos in to one.

1. We merge the `ebay` fork in to `socketplane`
2. We add myself, @hzhou8 and whomever else is interested as maintainers to the repository, updating the `MAINTAINERS` file in the process.
3. We donate the repository from the `socketplane` repository over to either `ovs` or `ovn-org`. This will provide the project with some governance too

/cc @trozet as a representative from `ovn-org`

# Code Impact

I've taken the liberty of merging the two repos [here](https://github.com/socketplane/libovsdb/tree/ebay-merge) for what this would look like.

The main differences are: 
1. It uses Github Actions for CI vs. Travis
1. A lot of linting issues, picked up by `golangci-lint` have been fixed

# Impact on users

I don't anticipate there being any negative impact on users. Only positives.

**Comment by hzhou8** [comment]
👋 @dave-tucker welcome back to libovsdb!

First of all I agree with your proposal. As you have seen in the README, this eBay fork of libovsdb was merely because of no response for my PR (small but critical) in the original socketplane repo. We initially forked it and fix internally in eBay so that go-ovn can work internally. Later since we (eBay) decided to open-source go-ovn, which depends on libovsdb and the fixes on top of it, we had to make sure the eBay modified version of libovsdb is open-sourced as well, hence this forked repo existed publicly. Now that you are back and socketplane repo is back to life, it makes sense to "upstream" back.

In fact, just a week before you came back, while I am trying my best to maintain these repos, I also started discussing internally in eBay about donating go-ovn and libovsdb to ovn-org/ovs, partly because it is getting more and more popular in upstream ovn-k8s community, and partly because of my personal changes. It is very similar to your proposal. However, there will be more management discussions in eBay, and I am not sure about legal processes, which could be slow (I guess there is no legal issue given the Apache license, but I am not an expert on that). It is kind of a coincidence that you came back and proposed this at the right time!

I also briefly mentioned your proposal in today's OVN meeting. People are positive on this potential move (to either openvswitch or ovn-org).

I'll check with eBay management again and get back ASAP.

**Comment by trozet** [comment]
thanks @hzhou8

**Comment by dave-tucker** [comment]
@hzhou8 I've completed the merge with your LGTM over in socketplane/libovsdb#71 and I've also sent you an invite to the socketplane org which will add you to the `libovsdb-maintainers` group and grant you merge access. Should eBay management want to make any changes to the `NOTICE` file etc... I'm more than happy to accommodate them.
